### ISSUE TITLE
invalid fields in world.json

### ISSUE THREAD

**Issue by kakaroto** [WallaceMcGregor/foundry-the-veil#1]
Hola,

I noticed that the world.json has some invalid fields. The `languages` field should be an array of objects, not an array of strings.
See : https://foundryvtt.com/article/module-development/
```
"languages": [
    {
      "lang": "es",
      "name": "Spanish",
    }
]
```

The same for the `authors` field. Note that while `authors` appears in the documentation, it's not used anywhere by Foundry and you should instead use the `author` field as a single string :
```
"author": "WallaceMcGregor",
```

**Comment by WallaceMcGregor** [comment]
Thank you for your comments. I don't really know too much about these technical aspects and a friend set up the world.json for me some time ago. I'll change it right now.
