### ISSUE TITLE
Error al instalar módulo en Foundry 9 build 269

### ISSUE THREAD

**Issue by Andyvec** [WallaceMcGregor/foundry-the-veil#2]
Al intentar instalar este módulo en Foundry 9, build 269, la última versión mientras escribo este reporte, el plugin da un error y no completa su instalación.
Estoy utilizando la siguiente URL para el fichero manifest: https://raw.githubusercontent.com/WallaceMcGregor/foundry-the-veil/master/world.json
El mensaje tanto por pantalla como por consola solo dice lo siguiente:
"Error: The "path" argument must be of type string. Received undefined"

Como nuevo en Foundry y jugador de The Veil, me vendría genial poder contar con la funcionalidad que provee este módulo.
Muchas gracias desde ya.

**Comment by WallaceMcGregor** [comment]
Buenas

El mundo de The Veil está en el repositorio oficial de Foundry. Así que si vas a la sección de mundos y lo buscas, te deberá salir. No es un **módulo**, es un **mundo**, tenlo en cuenta. En cualquier caso, te digo que lo hice hace bastante tiempo, para la versión 0.8.9 (en la que todavía estoy) así que no sé si tendrá algún error en las versiones más actuales de Foundry/Sandbox.

Ya me dices si al menos puedes instalarlo.

**Comment by Andyvec** [comment]
Gracias por la indicación. Ahora si que lo he podido instalar.
Es necesario migrar los datos de Foundry a una versión anterior, pero en principio no noté ningún problema, incluso con mis mundos nuevos.

Tengo la sensación que el módulo no funciona correcta en las nuevas versiones de Foundry/Sandbox, pero necesito más tiempo para leer bien las instrucciones que has dejado y trastear con la herramienta. EN todo caso, abriré un nuevo issue si encuentro algo.

Entiendo que este issue puede cerrarse sin más.
